In [1]:
import sys
from pathlib import Path
import pandas as pd

# Add repo root to PYTHONPATH
HERE = Path().resolve()
PROJECT_ROOT = HERE.parents[0]   # notebooks → repo root
sys.path.insert(0, str(PROJECT_ROOT))

from prm_opt.run_s25_s26_v2 import run_s25_s26_v2
from prm_opt.optimise_prm_fleet_v2 import OptimiserConfig

In [2]:
VEHICLE_MODELS = {
    # ---------------- Ambulifts (current fleet) ----------------
    "AMB_14111": {"type": "Amb", "seatcap": 6, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},
    "AMB_14112": {"type": "Amb", "seatcap": 6, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},
    "AMB_OMN135": {"type": "Amb", "seatcap": 3, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},
    "AMB_OMN079": {"type": "Amb", "seatcap": 6, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},
    "AMB_OMN080": {"type": "Amb", "seatcap": 6, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},
    "AMB_14161": {"type": "Amb", "seatcap": 7, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},
    "AMB_14162": {"type": "Amb", "seatcap": 7, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},
    "AMB_14163": {"type": "Amb", "seatcap": 7, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},
    "AMB_79803": {"type": "Amb", "seatcap": 7, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},
    "AMB_79802": {"type": "Amb", "seatcap": 7, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},
    "AMB_79801": {"type": "Amb", "seatcap": 7, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},
    "AMB_79804": {"type": "Amb", "seatcap": 7, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},
    "AMB_79805": {"type": "Amb", "seatcap": 7, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},
    "AMB_79900": {"type": "Amb", "seatcap": 7, "wccap": 1, "staff": 2, "capex_hr": 500000 / (5 * 365 * 24), "is_future": False},

    # ---------------- Minibuses (current fleet) ----------------
    "MB_WJ160DR": {"type": "Mini", "seatcap": 6, "wccap": 2, "staff": 2, "capex_hr": 80000 / (5 * 365 * 24), "is_future": False},
    "MB_WJ160DT": {"type": "Mini", "seatcap": 6, "wccap": 2, "staff": 2, "capex_hr": 80000 / (5 * 365 * 24), "is_future": False},
    "MB_WJ160FD": {"type": "Mini", "seatcap": 6, "wccap": 2, "staff": 2, "capex_hr": 80000 / (5 * 365 * 24), "is_future": False},

    # ---------------- Future purchase options ----------------
    "MB_EV_10": {"type": "Mini", "seatcap": 10, "wccap": 1, "staff": 2, "capex_hr": 80000 / (5 * 365 * 24), "is_future": True},
    "MB_EV_18": {"type": "Mini", "seatcap": 18, "wccap": 1, "staff": 2, "capex_hr": 80000 / (5 * 365 * 24), "is_future": True},
}


config = OptimiserConfig(
    tau_amb_solo_mins=19,
    tau_amb_comb_mins=14,
    tau_mini_mins=14,
    tau_push_mins=15,
    handover_buffer_mins=5,
    arrival_sla_target_pct=0.98,
    arrival_sla_target_mins=20,
    boarding_offset_mins=40,
    staff_amb=2,
    staff_mini=2,
    staff_per_prm_push=1,
    max_future_copies_per_model=5,
    solver_relative_gap=-0.01,
)

In [3]:
results = run_s25_s26_v2(
    run_s25=True,
    s25_start="2025-04-01",
    s25_end="2025-04-30",

    run_s26=False,

    vehicle_models=VEHICLE_MODELS,
    config=config,

    output_dir="outputs/prm_v2",
    output_xlsx_name="prm_v2_s25_outputs.xlsx",

    run_p100=True,
    run_p90=True,
    run_fleet_report=False,

    max_ev10=5,
    max_ev18=5,
)

    ✓ S25 ingest complete (12,649 passengers)   [62.29s]
    ✓ Passenger dataset combined (12,649 passenger rows)   [0.00s]
    ✓ P100 built (5,380 flights)   [0.34s]
    P100 demand summary: 12,649 PRMs across 5,380 flights
    ✓ prepare_model_data started | flights=5,380   [0.00s]
    ✓ vehicle expansion complete | vehicles=27   [0.03s]
    ✓ ambulift intervals built | flights=5,380 ambulifts=14   [0.33s]
    ✓ minibus intervals built | minibuses=13   [0.05s]
    ✓ staff intervals built   [0.01s]
    ✓ ambulift overlaps built | overlaps=1,745,269   [320.96s]
    ✓ minibus overlaps built | overlaps=718,965   [116.13s]
    ✓ staff event matrix skipped; staff cost will use mode-level staff minutes   [0.00s]
    ✓ staff requirements and staff-minutes calculated   [0.01s]
    ✓ prepare_model_data complete | total=437.53s   [0.00s]
    ✓ sets built | F=5,380 AMB=14 MINI=13   [0.00s]
    ✓ variables built | x=26,900 amb=225,960 mini=139,880   [0.69s]
    ✓ ambulift overlap constraints built | 1,745,269   [16.22s]
    ✓ minibus overlap constraints built | 718,965   [4.09s]
    ✓ build_pyomo_model complete | total=21.07s   [0.07s]

================================================================================
Starting HiGHS solve
================================================================================
Flights=5,380 Vehicles=27
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 3142124 rows; 430437 cols; 6791850 nonzeros; 392777 integer variables (392777 binary)
Coefficient ranges:
  Matrix  [1e+00, 3e+01]
  Cost    [2e+00, 1e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 1e+00]
Presolving model
806156 rows, 185800 cols, 1797714 nonzeros 4s
384959 rows, 153985 cols, 1188146 nonzeros 22s
384959 rows, 153985 cols, 1188146 nonzeros 54s
Presolve reductions: rows 384959(-2757165); columns 153985(-276452); nonzeros 1188146(-5603704)

Solving MIP model with:
   384959 rows
   153985 cols (142908 binary, 0 integer, 11077 implied int., 0 continuous, 0 domain fixed)
   1188146 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            1982427015.881     Large        0      0      0         0    67.5s
 R       0       0         0   0.00%   190680.179119   994190664.2968    99.98%        0      0      0     45787   330.0s
         0       0         0   0.00%   190762.879119   994190664.2968    99.98%     1302    161      0     46570   359.5s
         0       0         0   0.00%   191067.136694   994190664.2968    99.98%     1524    315      0     47337   368.0s
         0       0         0   0.00%   191673.015982   994190664.2968    99.98%     1659    440      0     48107   378.3s
         0       0         0   0.00%   191904.015982   994190664.2968    99.98%     1691    493      0     50202   399.1s
         0       0         0   0.00%   192003.515982   994190664.2968    99.98%     1783    497   3247     50341   419.1s
         0       0         0   0.00%   192114.862633   994190664.2968    99.98%     2022    518   3247     52352   566.3s
         0       0         0   0.00%   192177.2793     994190664.2968    99.98%     2108    524   3247     52719   574.1s
         0       0         0   0.00%   192231.390411   994190664.2968    99.98%     2154    529   3247     52962   579.5s
         0       0         0   0.00%   192237.890411   994190664.2968    99.98%     2301    532   3247     52983   610.3s
         0       0         0   0.00%   192255.890411   994190664.2968    99.98%     2401    536   3247     53067   634.1s
         0       0         0   0.00%   192416.557078   994190664.2968    99.98%     2517    542   3247     53231   652.5s
         0       0         0   0.00%   192418.7793     994190664.2968    99.98%     2577    547   3247     53667   666.5s
         0       0         0   0.00%   192457.2793     994190664.2968    99.98%     2627    556   3247     54430   680.3s
         0       0         0   0.00%   192457.2793     994190664.2968    99.98%     2760    564   3247     54481   713.3s
         0       0         0   0.00%   192457.2793     994190664.2968    99.98%     2854    500   3247     54513   729.3s
         0       0         0   0.00%   192503.2793     994190664.2968    99.98%     2901    505   3247     54681   741.2s
         0       0         0   0.00%   192547.2793     994190664.2968    99.98%     2981    508   3247     54696   752.5s
         0       0         0   0.00%   192553.7793     994190664.2968    99.98%     3054    512   3247     54735   767.5s

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   192553.7793     994190664.2968    99.98%     3136    515   3247     54749   780.3s
         0       0         0   0.00%   192553.7793     994190664.2968    99.98%     3198    509   3247     54763   793.1s
         0       0         0   0.00%   192553.7793     994190664.2968    99.98%     3350    511   3247     54790   830.1s
 L       0       0         0   0.00%   192553.7793     193096.296804      0.28%     3350    511   3247     54790  1481.1s
         0       0         0   0.00%   192553.7793     193096.296804      0.28%     3446    515   3247     84456  1517.9s

37.7% inactive integer columns, restarting
Model after restart has 180432 rows, 87412 cols (87412 bin., 0 int., 0 impl., 0 cont., 0 dom.fix.), and 619228 nonzeros

         0       0         0   0.00%   192553.7793     193096.296804      0.28%      445      0      0     84456  1532.2s
         0       0         0   0.00%   192553.7793     193096.296804      0.28%      445    173     38    135659  1652.7s
         0       0         0   0.00%   192891.157078   193096.296804      0.11%     1472    177     38    136733  1670.4s
         0       0         0   0.00%   192895.557078   193096.296804      0.10%     2292    183     38    137440  1688.0s
         0       0         0   0.00%   192895.557078   193096.296804      0.10%     2422    186     38    137462  1694.2s
         0       0         0   0.00%   192895.557078   193096.296804      0.10%     2514    187     38    137474  1702.0s
         0       0         0   0.00%   192895.557078   193096.296804      0.10%     2675    188     38    137475  1713.1s
         0       0         0   0.00%   192895.557078   193096.296804      0.10%     2757    189     38    137483  1722.1s
         0       0         0   0.00%   192895.557078   193096.296804      0.10%     2871    191     38    137501  1730.4s
         0       0         0   0.00%   192895.557078   193096.296804      0.10%     3064    194     38    137543  1746.0s
         0       0         0   0.00%   192895.557078   193096.296804      0.10%     3166    195     38    137554  1754.7s
         0       0         0   0.00%   192895.557078   193096.296804      0.10%     3337    197     38    137597  1767.2s
         0       0         0   0.00%   192895.557078   193096.296804      0.10%     3487    200     38    137636  1781.5s

Symmetry detection completed in 57.9s
Found 971 generator(s) and 295 full orbitope(s) acting on 5925 columns

 T       0       0         0   0.00%   192895.557078   192920.388128      0.01%     3487    198     59    137636  2687.4s
        65       9         1   0.29%   192895.557078   192920.388128      0.01%     3490    198     92    313448  2712.9s

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 L      65       7         1   0.39%   192895.557078   192918.388128      0.01%     4504    231     94    315132  2841.3s
        71      12         1   0.42%   192895.557078   192918.388128      0.01%     4504    231     94    344906  2855.4s
        88      27         1   0.42%   192895.557078   192918.388128      0.01%     5515    219    112    377947  2939.1s
        88      26         1   0.81%   192895.557078   192918.388128      0.01%     7522    266    113    382922  2951.9s
        89      24         2   5.49%   192895.557078   192918.388128      0.01%     8525    280    113    393657  2979.6s
        90      23         2  17.99%   192895.557078   192918.388128      0.01%    10286    336    113    415170  3037.5s
        91      22         2  42.99%   192895.557078   192918.388128      0.01%    11292    363    114    427774  3063.1s
        92      21         3  49.24%   192895.557078   192918.388128      0.01%    11292    363    114    433001  3074.1s
        93      20         4  49.29%   192895.557078   192918.388128      0.01%    11292    363    114    435757  3079.5s
        96      17         6  74.59%   192895.557078   192918.388128      0.01%     8447    371    114    443753  3094.5s
        97      16         7  74.98%   192895.557078   192918.388128      0.01%     8447    371    114    448030  3101.1s
        98      15         8  87.48%   192895.557078   192918.388128      0.01%     8448    371    114    456425  3120.3s
       101      12        11  96.88%   192897.557078   192918.388128      0.01%     8448    371    124    460857  3128.4s
       102      11        12  96.88%   192897.557078   192918.388128      0.01%     8448    371    124    464538  3134.4s
       108       5        18  96.97%   192897.557078   192918.388128      0.01%     8448    371    124    466041  3140.6s
       113       0        23 100.00%   192899.362253   192918.388128      0.01%     8448    371    124    466099  3142.9s

Solving report
  Status            Optimal
  Primal bound      192918.388128
  Dual bound        192899.365297
  Gap               0.00986% (tolerance: 0.01%)
  P-D integral      1412.19223172
  Solution status   feasible
                    192918.388128 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            3142.89
  Max sub-MIP depth 3
  Nodes             113
  Repair LPs        0
  LP iterations     466099
                    169387 (strong br.)
                    39067 (separation)
                    68105 (heuristics)
    ✓ P100 optimisation complete   [3707.04s]

[P100 fleet utilisation]
     vehicle_group vehicle_type  seatcap  wccap  current_available  \
0    Amb_3seat_1wc          Amb        3      1                  1
1    Amb_6seat_1wc          Amb        6      1                  4
2    Amb_7seat_1wc          Amb        7      1                  9
3  Mini_10seat_1wc         Mini       10      1                  0
4  Mini_18seat_1wc         Mini       18      1                  0
5   Mini_6seat_2wc         Mini        6      2                  3

   future_candidates_available  used_at_least_once  peak_concurrent_used  \
0                            0                   0                     0
1                            0                   3                     3
2                            0                   4                     4
3                            5                   0                     0
4                            5                   0                     0
5                            0                   3                     3

   required_for_schedule  gap_vs_current  surplus_vs_current  future_bought
0                      0               0                   1              0
1                      3               0                   1              0
2                      4               0                   5              0
3                      0               0                   0              0
4                      0               0                   0              0
5                      3               0                   0              0
    ✓ P90 built (5,380 flights)   [0.90s]
    P90 demand summary: 11,552 PRMs across 5,380 flights
    ✓ prepare_model_data started | flights=5,380   [0.00s]
    ✓ vehicle expansion complete | vehicles=27   [0.07s]
    ✓ ambulift intervals built | flights=5,380 ambulifts=14   [0.56s]
    ✓ minibus intervals built | minibuses=13   [0.06s]
    ✓ staff intervals built   [0.01s]
    ✓ ambulift overlaps built | overlaps=1,689,108   [467.48s]
    ✓ minibus overlaps built | overlaps=717,847   [120.20s]
    ✓ staff event matrix skipped; staff cost will use mode-level staff minutes   [0.00s]
    ✓ staff requirements and staff-minutes calculated   [0.02s]
    ✓ prepare_model_data complete | total=588.40s   [0.00s]
    ✓ sets built | F=5,380 AMB=14 MINI=13   [0.00s]
    ✓ variables built | x=26,900 amb=225,960 mini=139,880   [0.28s]
    ✓ ambulift overlap constraints built | 1,689,108   [27.10s]
    ✓ minibus overlap constraints built | 717,847   [5.47s]
    ✓ build_pyomo_model complete | total=32.97s   [0.11s]

================================================================================
Starting HiGHS solve
================================================================================
Flights=5,380 Vehicles=27
Running HiGHS 1.14.0 (git hash: 7df0786): Copyright (c) 2026 under MIT licence terms
MIP has 3084845 rows; 430437 cols; 6677292 nonzeros; 392777 integer variables (392777 binary)
Coefficient ranges:
  Matrix  [1e+00, 2e+01]
  Cost    [2e+00, 1e+06]
  Bound   [1e+00, 1e+00]
  RHS     [1e+00, 1e+00]
Presolving model
804196 rows, 185800 cols, 1793794 nonzeros 8s
384421 rows, 153985 cols, 1184968 nonzeros 25s
384421 rows, 153985 cols, 1184968 nonzeros 45s
Presolve reductions: rows 384421(-2700424); columns 153985(-276452); nonzeros 1184968(-5492324)

Solving MIP model with:
   384421 rows
   153985 cols (142908 binary, 0 integer, 11077 implied int., 0 continuous, 0 domain fixed)
   1184968 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; H => Heuristic;
     I => Shifting; J => Feasibility jump; L => Sub-MIP; P => Empty MIP; R => Randomized rounding;
     S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution; Y => HiGHS solution;
     Z => ZI Round; l => Trivial lower; p => Trivial point; u => Trivial upper; z => Trivial zero

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            1960410092.881     Large        0      0      0         0    54.1s
 R       0       0         0   0.00%   186337.913336   628186360.0502    99.97%        0      0      0     43178   179.5s
         0       0         0   0.00%   186339.29376    628186360.0502    99.97%     1196     40      0     60472   417.1s
         0       0         0   0.00%   186341.049315   628186360.0502    99.97%     2233     79      0     62037   433.9s
         0       0         0   0.00%   186444.057078   628186360.0502    99.97%     2390    118      0     66372   459.0s
         0       0         0   0.00%   186600.557078   628186360.0502    99.97%     3428    153      0     66940   474.1s
         0       0         0   0.00%   186609.057078   628186360.0502    99.97%     3643    159   1703     67442   506.2s
         0       0         0   0.00%   186621.890411   628186360.0502    99.97%     3702    164   1703     67514   514.7s
         0       0         0   0.00%   186631.557078   628186360.0502    99.97%     4006    167   1703     67524   533.8s
         0       0         0   0.00%   186632.557078   628186360.0502    99.97%     4224    170   1703     67566   546.7s
         0       0         0   0.00%   186632.557078   628186360.0502    99.97%     4560    171   1703     67604   565.4s
         0       0         0   0.00%   186632.557078   628186360.0502    99.97%     4836    172   1703     67618   584.7s
         0       0         0   0.00%   186632.557078   628186360.0502    99.97%     5099    173   1703     67621   613.4s
         0       0         0   0.00%   186632.557078   628186360.0502    99.97%     5179    174   1703     67636   634.7s
 L       0       0         0   0.00%   186632.557078   186831.296804      0.11%     5179    174   1703     67636  1031.7s
         0       0         0   0.00%   186632.557078   186831.296804      0.11%     5207    176   1703    112669  1037.8s

38.8% inactive integer columns, restarting
Model after restart has 176975 rows, 86013 cols (86013 bin., 0 int., 0 impl., 0 cont., 0 dom.fix.), and 602922 nonzeros

         0       0         0   0.00%   186632.557078   186831.296804      0.11%      124      0      0    112669  1047.7s
         0       0         0   0.00%   186632.557078   186831.296804      0.11%      124     51      5    167934  1138.2s
         0       0         0   0.00%   186632.557078   186831.296804      0.11%     1148     63      5    168236  1150.3s
         0       0         0   0.00%   186632.557078   186831.296804      0.11%     1384     68      5    168303  1156.3s

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   186632.557078   186831.296804      0.11%     1474     78      5    169087  1167.2s
         0       0         0   0.00%   186632.557078   186831.296804      0.11%     1670     94      5    169444  1173.7s
         0       0         0   0.00%   186632.557078   186831.296804      0.11%     1850     99      5    169476  1179.0s
         0       0         0   0.00%   186632.557078   186831.296804      0.11%     1931    101      5    169510  1186.6s

Symmetry detection completed in 45.9s
Found 1082 generator(s) and 276 full orbitope(s) acting on 6087 columns

 T       0       0         0   0.00%   186632.557078   186655.388128      0.01%     1931     86     26    169510  1753.8s
        59       5         1   4.69%   186632.557078   186655.388128      0.01%     1934     86     30    353521  1811.5s
        64       8         1   5.08%   186632.557078   186655.388128      0.01%     2951    120     32    367356  1838.3s
        68      10         1   6.64%   186632.557078   186655.388128      0.01%     3954    109     34    380347  1867.1s
        72      12         1   9.77%   186632.557078   186655.388128      0.01%     4959    119     36    394461  1896.4s
        79      17         1  10.55%   186632.557078   186655.388128      0.01%     6049    127     38    426168  1961.5s
        88      24         1  10.60%   186632.557078   186655.388128      0.01%     7051    134     38    446370  2015.7s
        89      23         1  12.16%   186632.557078   186655.388128      0.01%     9062    137     40    455572  2033.4s
        90      22         1  15.28%   186632.557078   186655.388128      0.01%    10065    152     40    460559  2045.1s
        94      24         1  15.30%   186632.557078   186655.388128      0.01%     9723    186     42    490283  2099.7s
        95      23         1  15.49%   186632.557078   186655.388128      0.01%    10821    204     44    494123  2111.0s
        97      21         3  19.01%   186632.557078   186655.388128      0.01%    10821    204     44    498071  2118.8s

In [ ]:
results = run_s25_s26_v2(
    run_s25=False,

    run_s26=True,
    s26_start="2026-04-01",
    s26_end="2026-10-31",

    penetration_rates=penetration_rates,
    ssr_mix=ssr_mix,
    stand_actuals=stand_actuals,
    stand_dist=stand_dist,

    penetration_uplift=1.0,

    vehicle_models=VEHICLE_MODELS,
    config=config,

    output_dir="outputs/prm_v2",
    output_xlsx_name="prm_v2_s26_outputs.xlsx",

    run_p100=True,
    run_p90=True,
    run_fleet_report=True,

    max_ev10=5,
    max_ev18=5,
)

In [4]:
results["output_workbook_path"]

'outputs\\prm_v2\\prm_v2_s25_outputs.xlsx'

In [5]:
results["outputs_p100"]["sla_summary"]

,arrival_flights,arrival_breached_flights,arrival_prms,arrival_prm_breaches,arrival_sla_pct,arrival_target_pct,arrival_meets_target,arrival_sla_target_mins,departure_flights,departure_prms,departure_prm_breaches,departure_sla_pct
0,2934,0,7547,0,100.0,98.0,1,20.0,2446,5102,0,100.0

In [6]:
results["outputs_p90"]["sla_summary"]

,arrival_flights,arrival_breached_flights,arrival_prms,arrival_prm_breaches,arrival_sla_pct,arrival_target_pct,arrival_meets_target,arrival_sla_target_mins,departure_flights,departure_prms,departure_prm_breaches,departure_sla_pct
0,2934,0,6801,0,100.0,98.0,1,20.0,2446,4751,0,100.0

In [7]:
results["fleet_requirements_p100"]

KeyError: 'fleet_requirements_p100'

In [8]:
results["recommended_p100"]

KeyError: 'recommended_p100'

In [9]:
results["fleet_requirements_p90"]

KeyError: 'fleet_requirements_p90'

In [10]:
results["recommended_p90"]

KeyError: 'recommended_p90'

In [ ]:
from datetime import date, timedelta
from calendar import monthrange
from pathlib import Path

import pandas as pd


MONTHS_TO_RUN = [
    (2025, 4),
    (2025, 5),
    (2025, 6),
    (2025, 7),
    (2025, 8),
    (2025, 9),
    (2025, 10),

    (2026, 4),
    (2026, 5),
    (2026, 6),
    (2026, 7),
    (2026, 8),
    (2026, 9),
    (2026, 10),
]

today = date.today()

monthly_rows = []

monthly_dir = Path(
    "outputs/prm_v2/monthly_summary"
)

monthly_dir.mkdir(
    parents=True,
    exist_ok=True,
)


for year, month in MONTHS_TO_RUN:

    month_start = date(year, month, 1)

    month_end = date(
        year,
        month,
        monthrange(year, month)[1],
    )

    print(
        "\n"
        + "=" * 80
    )

    print(
        f"Running {month_start:%Y-%m}"
    )

    try:

        kwargs = {}

        run_s25 = False
        run_s26 = False

        # --------------------------------------------------
        # Fully historical month
        # --------------------------------------------------

        if month_end < today:

            run_s25 = True

            kwargs["s25_start"] = str(month_start)
            kwargs["s25_end"] = str(month_end)

        # --------------------------------------------------
        # Fully future month
        # --------------------------------------------------

        elif month_start > today:

            run_s26 = True

            kwargs["s26_start"] = str(month_start)
            kwargs["s26_end"] = str(month_end)

        # --------------------------------------------------
        # Current month split
        # --------------------------------------------------

        else:

            yesterday = today - timedelta(days=1)

            run_s25 = True
            run_s26 = True

            kwargs["s25_start"] = str(month_start)
            kwargs["s25_end"] = str(yesterday)

            kwargs["s26_start"] = str(today)
            kwargs["s26_end"] = str(month_end)

        result = run_s25_s26_v2(

            run_s25=run_s25,
            run_s26=run_s26,

            vehicle_models=VEHICLE_MODELS,
            config=config,

            run_p100=True,
            run_p90=True,

            run_fleet_report=True,

            fleet_report_policy="if_needed",
            current_fleet_only_first=True,

            output_dir=str(monthly_dir),
            output_xlsx_name=f"{year}_{month:02d}.xlsx",

            max_ev10=5,
            max_ev18=5,

            **kwargs,
        )

        # ==========================================
        # P100
        # ==========================================

        p100 = result["outputs_p100"]

        p100_fleet = p100["fleet_utilisation"]

        monthly_rows.append(
            {
                "month": month_start.strftime("%Y-%m"),
                "mode": "P100",

                "arrival_sla_pct":
                    float(
                        p100["sla_summary"]
                        .iloc[0]["arrival_sla_pct"]
                    ),

                "peak_amb":
                    int(
                        p100_fleet.loc[
                            p100_fleet["vehicle_type"] == "Amb",
                            "required_for_schedule"
                        ].sum()
                    ),

                "peak_mini":
                    int(
                        p100_fleet.loc[
                            p100_fleet["vehicle_type"] == "Mini",
                            "required_for_schedule"
                        ].sum()
                    ),

                "peak_staff":
                    float(
                        p100["staff_summary"][
                            "staff_required"
                        ].max()
                    ),

                "fleet_expansion_required":
                    int(
                        result.get(
                            "p100_base_check",
                            pd.DataFrame(
                                [{"needs_fleet_expansion": 0}]
                            )
                        ).iloc[0]["needs_fleet_expansion"]
                    ),

                "current_fleet_sufficient":
                    int(
                        result.get(
                            "p100_base_check",
                            pd.DataFrame(
                                [{"current_fleet_sufficient": 1}]
                            )
                        ).iloc[0]["current_fleet_sufficient"]
                    ),

                "recommended_scenario":
                    (
                        result["recommended_p100"]
                        .iloc[0]["scenario"]
                    )
                    if (
                        "recommended_p100" in result
                        and len(result["recommended_p100"]) > 0
                        and "scenario" in result["recommended_p100"].columns
                    )
                    else "CURRENT_FLEET_OK",
            }
        )

        # ==========================================
        # P90
        # ==========================================

        p90 = result["outputs_p90"]

        p90_fleet = p90["fleet_utilisation"]

        monthly_rows.append(
            {
                "month": month_start.strftime("%Y-%m"),
                "mode": "P90",

                "arrival_sla_pct":
                    float(
                        p90["sla_summary"]
                        .iloc[0]["arrival_sla_pct"]
                    ),

                "peak_amb":
                    int(
                        p90_fleet.loc[
                            p90_fleet["vehicle_type"] == "Amb",
                            "required_for_schedule"
                        ].sum()
                    ),

                "peak_mini":
                    int(
                        p90_fleet.loc[
                            p90_fleet["vehicle_type"] == "Mini",
                            "required_for_schedule"
                        ].sum()
                    ),

                "peak_staff":
                    float(
                        p90["staff_summary"][
                            "staff_required"
                        ].max()
                    ),

                "fleet_expansion_required":
                    int(
                        result.get(
                            "p90_base_check",
                            pd.DataFrame(
                                [{"needs_fleet_expansion": 0}]
                            )
                        ).iloc[0]["needs_fleet_expansion"]
                    ),

                "current_fleet_sufficient":
                    int(
                        result.get(
                            "p90_base_check",
                            pd.DataFrame(
                                [{"current_fleet_sufficient": 1}]
                            )
                        ).iloc[0]["current_fleet_sufficient"]
                    ),

                "recommended_scenario":
                    (
                        result["recommended_p90"]
                        .iloc[0]["scenario"]
                    )
                    if (
                        "recommended_p90" in result
                        and len(result["recommended_p90"]) > 0
                        and "scenario" in result["recommended_p90"].columns
                    )
                    else "CURRENT_FLEET_OK",
            }
        )

        # --------------------------------------
        # SAVE AFTER EVERY MONTH
        # --------------------------------------

        pd.DataFrame(
            monthly_rows
        ).to_excel(
            monthly_dir /
            "monthly_summary.xlsx",
            index=False,
        )

        print(
            f"Completed {month_start:%Y-%m}"
        )

    except Exception as e:

        print(
            f"FAILED {month_start:%Y-%m}"
        )

        print(e)

        # Save progress even if a month fails

        pd.DataFrame(
            monthly_rows
        ).to_excel(
            monthly_dir /
            "monthly_summary.xlsx",
            index=False,
        )

        continue


monthly_summary = pd.DataFrame(
    monthly_rows
)

monthly_summary

================================================================================
Running 2025-04
FAILED 2025-04
(pyodbc.Error) ('FA004', "[FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0) (SQLDriverConnect); [FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0)")
(Background on this error at: https://sqlalche.me/e/20/dbapi)

================================================================================
Running 2025-05
FAILED 2025-05
(pyodbc.Error) ('FA004', "[FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: 357d19a0-0c5d-4a23-b392-c4bfd9513400 Correlation ID: 61c95ae0-4da4-4d62-9d25-00eb09d7708b Timestamp: 2026-07-14 05:25:16Z (0) (SQLDriverConnect); [FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: 357d19a0-0c5d-4a23-b392-c4bfd9513400 Correlation ID: 61c95ae0-4da4-4d62-9d25-00eb09d7708b Timestamp: 2026-07-14 05:25:16Z (0)")
(Background on this error at: https://sqlalche.me/e/20/dbapi)

================================================================================
Running 2025-06
FAILED 2025-06
(pyodbc.Error) ('FA004', "[FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0) (SQLDriverConnect); [FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0)")
(Background on this error at: https://sqlalche.me/e/20/dbapi)

================================================================================
Running 2025-07
FAILED 2025-07
(pyodbc.Error) ('FA004', "[FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0) (SQLDriverConnect); [FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0)")
(Background on this error at: https://sqlalche.me/e/20/dbapi)

================================================================================
Running 2025-08
FAILED 2025-08
(pyodbc.Error) ('FA004', "[FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0) (SQLDriverConnect); [FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0)")
(Background on this error at: https://sqlalche.me/e/20/dbapi)

================================================================================
Running 2025-09
FAILED 2025-09
(pyodbc.Error) ('FA004', "[FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0) (SQLDriverConnect); [FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0)")
(Background on this error at: https://sqlalche.me/e/20/dbapi)

================================================================================
Running 2025-10
FAILED 2025-10
(pyodbc.Error) ('FA004', "[FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0) (SQLDriverConnect); [FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0)")
(Background on this error at: https://sqlalche.me/e/20/dbapi)

================================================================================
Running 2026-04
FAILED 2026-04
(pyodbc.Error) ('FA004', "[FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0) (SQLDriverConnect); [FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0)")
(Background on this error at: https://sqlalche.me/e/20/dbapi)

================================================================================
Running 2026-05
FAILED 2026-05
(pyodbc.Error) ('FA004', "[FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0) (SQLDriverConnect); [FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0)")
(Background on this error at: https://sqlalche.me/e/20/dbapi)

================================================================================
Running 2026-06
FAILED 2026-06
(pyodbc.Error) ('FA004', "[FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0) (SQLDriverConnect); [FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user 'jamie_douglas@edinburghairport.com' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').\r\nError code 0xCAA2000C; state 10\r\nAADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'. Trace ID: ed944962-cf2c-4e4a-b651-fd45437d3400 Correlation ID: 837a8d79-ab04-49d8-8551-e295743b60cd Timestamp: 2026-07-14 05:25:15Z (0)")
(Background on this error at: https://sqlalche.me/e/20/dbapi)

================================================================================
Running 2026-07
FAILED 2026-07
name 'penetration_rates' is not defined

================================================================================
Running 2026-08
FAILED 2026-08
name 'penetration_rates' is not defined

================================================================================
Running 2026-09
FAILED 2026-09
name 'penetration_rates' is not defined

================================================================================
Running 2026-10
FAILED 2026-10
name 'penetration_rates' is not defined

Empty DataFrame
Columns: []
Index: []